name: trust_guard
description: A user dashboard app with transactions, leaderboard, settings, and chat support.
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.2

  # Charts & Animations
  fl_chart: ^0.63.0
  animations: ^2.0.10

  # Notifications & Toast Messages
  flutter_local_notifications: ^16.2.0
  fluttertoast: ^8.2.4

  # Storage & Preferences
  shared_preferences: ^2.2.1

  # Internationalization
  intl: ^0.18.1

  # Chat UI for Messaging Feature
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
